Prepending /projappl/project_2003107/anaconda3/envs/analytics-zoo/lib/python3.6/site-packages/bigdl/share/conf/spark-bigdl.conf to sys.path
Adding /projappl/project_2003107/anaconda3/envs/analytics-zoo/lib/python3.6/site-packages/zoo/share/lib/analytics-zoo-bigdl_0.10.0-spark_2.4.3-0.8.1-jar-with-dependencies.jar to BIGDL_JARS
Prepending /projappl/project_2003107/anaconda3/envs/analytics-zoo/lib/python3.6/site-packages/zoo/share/conf/spark-analytics-zoo.conf to sys.path
Current pyspark location is : /projappl/project_2003107/anaconda3/envs/analytics-zoo/lib/python3.6/site-packages/pyspark/__init__.py
Start to getOrCreate SparkContext
Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/scratch/project_2003107
Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/scratch/project_2003107
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/projappl/project_2003107/anaconda3/envs/analytics-zoo/lib/python3.6/site-packages/pyspark/jars/spark-unsafe_2.11-2.4.3.jar) to method java.nio.Bits.unaligned()
WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2020-09-28 10:50:22 WARN  NativeCodeLoader:62 - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).

User settings:

   KMP_AFFINITY=granularity=fine,compact,1,0
   KMP_BLOCKTIME=0
   KMP_DUPLICATE_LIB_OK=True
   KMP_INIT_AT_FORK=FALSE
   KMP_SETTINGS=1
   OMP_NUM_THREADS=1

Effective settings:

   KMP_ABORT_DELAY=0
   KMP_ADAPTIVE_LOCK_PROPS='1,1024'
   KMP_ALIGN_ALLOC=64
   KMP_ALL_THREADPRIVATE=160
   KMP_ATOMIC_MODE=2
   KMP_BLOCKTIME=0
   KMP_CPUINFO_FILE: value is not defined
   KMP_DETERMINISTIC_REDUCTION=false
   KMP_DEVICE_THREAD_LIMIT=2147483647
   KMP_DISP_HAND_THREAD=false
   KMP_DISP_NUM_BUFFERS=7
   KMP_DUPLICATE_LIB_OK=true
   KMP_FORCE_REDUCTION: value is not defined
   KMP_FOREIGN_THREADS_THREADPRIVATE=true
   KMP_FORKJOIN_BARRIER='2,2'
   KMP_FORKJOIN_BARRIER_PATTERN='hyper,hyper'
   KMP_FORKJOIN_FRAMES=true
   KMP_FORKJOIN_FRAMES_MODE=3
   KMP_GTID_MODE=3
   KMP_HANDLE_SIGNALS=false
   KMP_HOT_TEAMS_MAX_LEVEL=1
   KMP_HOT_TEAMS_MODE=0
   KMP_INIT_AT_FORK=true
   KMP_INIT_WAIT=2048
   KMP_ITT_PREPARE_DELAY=0
   KMP_LIBRARY=throughput
   KMP_LOCK_KIND=queuing
   KMP_MALLOC_POOL_INCR=1M
   KMP_NEXT_WAIT=1024
   KMP_NUM_LOCKS_IN_BLOCK=1
   KMP_PLAIN_BARRIER='2,2'
   KMP_PLAIN_BARRIER_PATTERN='hyper,hyper'
   KMP_REDUCTION_BARRIER='1,1'
   KMP_REDUCTION_BARRIER_PATTERN='hyper,hyper'
   KMP_SCHEDULE='static,balanced;guided,iterative'
   KMP_SETTINGS=true
   KMP_SPIN_BACKOFF_PARAMS='4096,100'
   KMP_STACKOFFSET=64
   KMP_STACKPAD=0
   KMP_STACKSIZE=4M
   KMP_STORAGE_MAP=false
   KMP_TASKING=2
   KMP_TASKLOOP_MIN_TASKS=0
   KMP_TASK_STEALING_CONSTRAINT=1
   KMP_TEAMS_THREAD_LIMIT=40
   KMP_TOPOLOGY_METHOD=all
   KMP_USER_LEVEL_MWAIT=false
   KMP_VERSION=false
   KMP_WARNINGS=true
   OMP_AFFINITY_FORMAT='OMP: pid %P tid %T thread %n bound to OS proc set {%a}'
   OMP_ALLOCATOR=omp_default_mem_alloc
   OMP_CANCELLATION=false
   OMP_DEFAULT_DEVICE=0
   OMP_DISPLAY_AFFINITY=false
   OMP_DISPLAY_ENV=false
   OMP_DYNAMIC=false
   OMP_MAX_ACTIVE_LEVELS=2147483647
   OMP_MAX_TASK_PRIORITY=0
   OMP_NESTED=false
   OMP_NUM_THREADS='1'
   OMP_PLACES: value is not defined
   OMP_PROC_BIND='intel'
   OMP_SCHEDULE='static'
   OMP_STACKSIZE=4M
   OMP_TARGET_OFFLOAD=DEFAULT
   OMP_THREAD_LIMIT=2147483647
   OMP_TOOL=enabled
   OMP_TOOL_LIBRARIES: value is not defined
   OMP_WAIT_POLICY=PASSIVE
   KMP_AFFINITY='noverbose,warnings,respect,granularity=fine,compact,1,0'

cls.getname: com.intel.analytics.bigdl.python.api.Sample
BigDLBasePickler registering: bigdl.util.common  Sample
cls.getname: com.intel.analytics.bigdl.python.api.EvaluatedResult
BigDLBasePickler registering: bigdl.util.common  EvaluatedResult
cls.getname: com.intel.analytics.bigdl.python.api.JTensor
BigDLBasePickler registering: bigdl.util.common  JTensor
cls.getname: com.intel.analytics.bigdl.python.api.JActivity
BigDLBasePickler registering: bigdl.util.common  JActivity
Successfully got a SparkContext
2020-09-28 10:50:28,871	WARNING worker.py:1337 -- WARNING: Not updating worker name since `setproctitle` is not installed. Install this with `pip install setproctitle` (or ray[debug]) to enable monitoring of worker processes.
2020-09-28 10:50:28,872	INFO node.py:498 -- Process STDOUT and STDERR is being redirected to /tmp/ray/session_2020-09-28_10-50-28_872061_202869/logs.
2020-09-28 10:50:29,012	INFO services.py:409 -- Waiting for redis server at 127.0.0.1:63178 to respond...
2020-09-28 10:50:30,013	INFO services.py:414 -- Failed to connect to the redis server, retrying.
2020-09-28 10:50:30,014	INFO services.py:409 -- Waiting for redis server at 127.0.0.1:63178 to respond...
2020-09-28 10:50:30,498	INFO services.py:409 -- Waiting for redis server at 127.0.0.1:15156 to respond...
2020-09-28 10:50:30,500	INFO services.py:806 -- Starting Redis shard with 10.0 GB max memory.
2020-09-28 10:50:30,559	INFO node.py:512 -- Process STDOUT and STDERR is being redirected to /tmp/ray/session_2020-09-28_10-50-28_872061_202869/logs.
2020-09-28 10:50:30,560	WARNING services.py:1298 -- Warning: Capping object memory store to 20.0GB. To increase this further, specify `object_store_memory` when calling ray.init() or ray start.
2020-09-28 10:50:30,560	INFO services.py:1446 -- Starting the Plasma object store with 20.0 GB memory using /dev/shm.
WARNING: Logging before InitGoogleLogging() is written to STDERR
E0928 10:50:30.661394 202869 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2020-09-28_10-50-28_872061_202869/sockets/plasma_store, retrying 300 more times
2020-09-28 10:50:33,512	WARNING bayesopt.py:69 -- `reward_attr` is deprecated and will be removed in a future version of Tune. Setting `metric=reward_metric` and `mode=max`.
2020-09-28 10:50:35,925	INFO tune.py:65 -- Did not find checkpoint file in /run/nvme/job_3505765/tmp/ray_results_ydabb94g/automl.
2020-09-28 10:50:35,930	INFO tune.py:233 -- Starting a new experiment.
== Status ==
Using FIFO scheduling algorithm.
Resources requested: 0/40 CPUs, 0/0 GPUs
Memory usage on this node: 31.8/403.8 GB

WARNING:tensorflow:From /projappl/project_2003107/anaconda3/envs/analytics-zoo/lib/python3.6/site-packages/ray/tune/logger.py:136: The name tf.VERSION is deprecated. Please use tf.version.VERSION instead.

WARNING:tensorflow:From /projappl/project_2003107/anaconda3/envs/analytics-zoo/lib/python3.6/site-packages/ray/tune/logger.py:141: The name tf.summary.FileWriter is deprecated. Please use tf.compat.v1.summary.FileWriter instead.

2020-09-28 10:50:36,231	WARNING util.py:64 -- The `start_trial` operation took 0.21433377265930176 seconds to complete, which may be a performance bottleneck.
== Status ==
Using FIFO scheduling algorithm.
Resources requested: 4/40 CPUs, 0/0 GPUs
Memory usage on this node: 31.8/403.8 GB
Result logdir: /run/nvme/job_3505765/tmp/ray_results_ydabb94g/automl
Number of trials: 10 ({'RUNNING': 1, 'PENDING': 9})
PENDING trials:
 - train_func_2_batch_size_log=9.3906,bayes_feature_DAY(timestamp)=0.31917,bayes_feature_HOUR(timestamp)=0.76933,bayes_feature_IS_AWAKE(timestamp)=0.59211,bayes_feature_IS_BUSY_HOURS(timestamp)=0.69108,bayes_feature_IS_WEEKEND(timestamp)=0.39827,bayes_feature_MONTH(timestamp)=0.43867,bayes_feature_WEEKDAY(timestamp)=0.86052,dropout_1=0.49048,dropout_2=0.29403,epochs=5,lr=0.0072309,lstm_1_units_float=113.17,lstm_2_units_float=115.35,past_seq_len=2:	PENDING
 - train_func_3_batch_size_log=5.4252,bayes_feature_DAY(timestamp)=0.32734,bayes_feature_HOUR(timestamp)=0.41888,bayes_feature_IS_AWAKE(timestamp)=0.9147,bayes_feature_IS_BUSY_HOURS(timestamp)=0.36884,bayes_feature_IS_WEEKEND(timestamp)=0.59478,bayes_feature_MONTH(timestamp)=0.97052,bayes_feature_WEEKDAY(timestamp)=0.67322,dropout_1=0.40756,dropout_2=0.29465,epochs=5,lr=0.0071785,lstm_1_units_float=108.16,lstm_2_units_float=10.195,past_seq_len=2:	PENDING
 - train_func_4_batch_size_log=8.7507,bayes_feature_DAY(timestamp)=0.9922,bayes_feature_HOUR(timestamp)=0.82372,bayes_feature_IS_AWAKE(timestamp)=0.49631,bayes_feature_IS_BUSY_HOURS(timestamp)=0.8525,bayes_feature_IS_WEEKEND(timestamp)=0.37226,bayes_feature_MONTH(timestamp)=0.61353,bayes_feature_WEEKDAY(timestamp)=0.93602,dropout_1=0.28808,dropout_2=0.28633,epochs=5,lr=0.0021703,lstm_1_units_float=10.324,lstm_2_units_float=89.46,past_seq_len=2:	PENDING
 - train_func_5_batch_size_log=6.0581,bayes_feature_DAY(timestamp)=0.48588,bayes_feature_HOUR(timestamp)=0.6441,bayes_feature_IS_AWAKE(timestamp)=0.33735,bayes_feature_IS_BUSY_HOURS(timestamp)=0.70188,bayes_feature_IS_WEEKEND(timestamp)=0.40271,bayes_feature_MONTH(timestamp)=0.71251,bayes_feature_WEEKDAY(timestamp)=0.78983,dropout_1=0.2307,dropout_2=0.32422,epochs=5,lr=0.0072496,lstm_1_units_float=57.702,lstm_2_units_float=13.994,past_seq_len=2:	PENDING
 - train_func_6_batch_size_log=7.6795,bayes_feature_DAY(timestamp)=0.76466,bayes_feature_HOUR(timestamp)=0.66042,bayes_feature_IS_AWAKE(timestamp)=0.96122,bayes_feature_IS_BUSY_HOURS(timestamp)=0.71059,bayes_feature_IS_WEEKEND(timestamp)=0.93238,bayes_feature_MONTH(timestamp)=0.39623,bayes_feature_WEEKDAY(timestamp)=0.39749,dropout_1=0.44222,dropout_2=0.3193,epochs=5,lr=0.0024882,lstm_1_units_float=119.3,lstm_2_units_float=49.732,past_seq_len=2:	PENDING
 - train_func_7_batch_size_log=8.7541,bayes_feature_DAY(timestamp)=0.8082,bayes_feature_HOUR(timestamp)=0.91831,bayes_feature_IS_AWAKE(timestamp)=0.73657,bayes_feature_IS_BUSY_HOURS(timestamp)=0.82566,bayes_feature_IS_WEEKEND(timestamp)=0.54423,bayes_feature_MONTH(timestamp)=0.48895,bayes_feature_WEEKDAY(timestamp)=0.92712,dropout_1=0.32843,dropout_2=0.48945,epochs=5,lr=0.006971,lstm_1_units_float=82.603,lstm_2_units_float=21.77,past_seq_len=2:	PENDING
 - train_func_8_batch_size_log=9.7474,bayes_feature_DAY(timestamp)=0.61494,bayes_feature_HOUR(timestamp)=0.70487,bayes_feature_IS_AWAKE(timestamp)=0.5857,bayes_feature_IS_BUSY_HOURS(timestamp)=0.46592,bayes_feature_IS_WEEKEND(timestamp)=0.93237,bayes_feature_MONTH(timestamp)=0.70158,bayes_feature_WEEKDAY(timestamp)=0.30201,dropout_1=0.38514,dropout_2=0.29799,epochs=5,lr=0.0057435,lstm_1_units_float=114.31,lstm_2_units_float=50.872,past_seq_len=2:	PENDING
 - train_func_9_batch_size_log=9.5427,bayes_feature_DAY(timestamp)=0.73635,bayes_feature_HOUR(timestamp)=0.31107,bayes_feature_IS_AWAKE(timestamp)=0.95061,bayes_feature_IS_BUSY_HOURS(timestamp)=0.78363,bayes_feature_IS_WEEKEND(timestamp)=0.99813,bayes_feature_MONTH(timestamp)=0.42064,bayes_feature_WEEKDAY(timestamp)=0.396,dropout_1=0.47978,dropout_2=0.40905,epochs=5,lr=0.001594,lstm_1_units_float=98.656,lstm_2_units_float=98.465,past_seq_len=2:	PENDING
 - train_func_10_batch_size_log=9.6151,bayes_feature_DAY(timestamp)=0.79807,bayes_feature_HOUR(timestamp)=0.38699,bayes_feature_IS_AWAKE(timestamp)=0.31392,bayes_feature_IS_BUSY_HOURS(timestamp)=0.31835,bayes_feature_IS_WEEKEND(timestamp)=0.31981,bayes_feature_MONTH(timestamp)=0.47235,bayes_feature_WEEKDAY(timestamp)=0.90202,dropout_1=0.36165,dropout_2=0.36585,epochs=5,lr=0.0085783,lstm_1_units_float=22.901,lstm_2_units_float=41.502,past_seq_len=2:	PENDING
RUNNING trials:
 - train_func_1_batch_size_log=7.0851,bayes_feature_DAY(timestamp)=0.80423,bayes_feature_HOUR(timestamp)=0.30008,bayes_feature_IS_AWAKE(timestamp)=0.51163,bayes_feature_IS_BUSY_HOURS(timestamp)=0.40273,bayes_feature_IS_WEEKEND(timestamp)=0.36464,bayes_feature_MONTH(timestamp)=0.43038,bayes_feature_WEEKDAY(timestamp)=0.54189,dropout_1=0.31903,dropout_2=0.36165,epochs=5,lr=0.0047728,lstm_1_units_float=90.226,lstm_2_units_float=32.534,past_seq_len=2:	RUNNING

2020-09-28 10:50:36,475	WARNING util.py:64 -- The `start_trial` operation took 0.23836326599121094 seconds to complete, which may be a performance bottleneck.
2020-09-28 10:50:36,784	WARNING util.py:64 -- The `start_trial` operation took 0.22718334197998047 seconds to complete, which may be a performance bottleneck.
2020-09-28 10:50:37,075	WARNING util.py:64 -- The `start_trial` operation took 0.27043819427490234 seconds to complete, which may be a performance bottleneck.
2020-09-28 10:50:37,242	WARNING util.py:64 -- The `start_trial` operation took 0.1282815933227539 seconds to complete, which may be a performance bottleneck.
2020-09-28 10:50:37,503	WARNING util.py:64 -- The `start_trial` operation took 0.150146484375 seconds to complete, which may be a performance bottleneck.
2020-09-28 10:50:37,782	WARNING util.py:64 -- The `start_trial` operation took 0.2646162509918213 seconds to complete, which may be a performance bottleneck.
2020-09-28 10:50:37,954	WARNING util.py:64 -- The `start_trial` operation took 0.15643548965454102 seconds to complete, which may be a performance bottleneck.
2020-09-28 10:50:38,089	WARNING util.py:64 -- The `start_trial` operation took 0.1239023208618164 seconds to complete, which may be a performance bottleneck.
Exception in thread ray_import_thread:
Traceback (most recent call last):
  File "/projappl/project_2003107/anaconda3/envs/analytics-zoo/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/projappl/project_2003107/anaconda3/envs/analytics-zoo/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/projappl/project_2003107/anaconda3/envs/analytics-zoo/lib/python3.6/site-packages/ray/import_thread.py", line 69, in _run
    msg = import_pubsub_client.get_message()
  File "/projappl/project_2003107/anaconda3/envs/analytics-zoo/lib/python3.6/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/projappl/project_2003107/anaconda3/envs/analytics-zoo/lib/python3.6/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/projappl/project_2003107/anaconda3/envs/analytics-zoo/lib/python3.6/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/projappl/project_2003107/anaconda3/envs/analytics-zoo/lib/python3.6/site-packages/redis/connection.py", line 321, in can_read
    return self._buffer and self._buffer.can_read(timeout)
  File "/projappl/project_2003107/anaconda3/envs/analytics-zoo/lib/python3.6/site-packages/redis/connection.py", line 231, in can_read
    raise_on_timeout=False)
  File "/projappl/project_2003107/anaconda3/envs/analytics-zoo/lib/python3.6/site-packages/redis/connection.py", line 201, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.

Exception in thread ray_listen_error_messages:
Traceback (most recent call last):
  File "/projappl/project_2003107/anaconda3/envs/analytics-zoo/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/projappl/project_2003107/anaconda3/envs/analytics-zoo/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/projappl/project_2003107/anaconda3/envs/analytics-zoo/lib/python3.6/site-packages/ray/worker.py", line 1652, in listen_error_messages_raylet
    msg = worker.error_message_pubsub_client.get_message()
  File "/projappl/project_2003107/anaconda3/envs/analytics-zoo/lib/python3.6/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/projappl/project_2003107/anaconda3/envs/analytics-zoo/lib/python3.6/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/projappl/project_2003107/anaconda3/envs/analytics-zoo/lib/python3.6/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/projappl/project_2003107/anaconda3/envs/analytics-zoo/lib/python3.6/site-packages/redis/connection.py", line 321, in can_read
    return self._buffer and self._buffer.can_read(timeout)
  File "/projappl/project_2003107/anaconda3/envs/analytics-zoo/lib/python3.6/site-packages/redis/connection.py", line 231, in can_read
    raise_on_timeout=False)
  File "/projappl/project_2003107/anaconda3/envs/analytics-zoo/lib/python3.6/site-packages/redis/connection.py", line 201, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.

Exception in thread ray_print_logs:
Traceback (most recent call last):
  File "/projappl/project_2003107/anaconda3/envs/analytics-zoo/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/projappl/project_2003107/anaconda3/envs/analytics-zoo/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/projappl/project_2003107/anaconda3/envs/analytics-zoo/lib/python3.6/site-packages/ray/worker.py", line 1550, in print_logs
    msg = pubsub_client.get_message()
  File "/projappl/project_2003107/anaconda3/envs/analytics-zoo/lib/python3.6/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/projappl/project_2003107/anaconda3/envs/analytics-zoo/lib/python3.6/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/projappl/project_2003107/anaconda3/envs/analytics-zoo/lib/python3.6/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/projappl/project_2003107/anaconda3/envs/analytics-zoo/lib/python3.6/site-packages/redis/connection.py", line 321, in can_read
    return self._buffer and self._buffer.can_read(timeout)
  File "/projappl/project_2003107/anaconda3/envs/analytics-zoo/lib/python3.6/site-packages/redis/connection.py", line 231, in can_read
    raise_on_timeout=False)
  File "/projappl/project_2003107/anaconda3/envs/analytics-zoo/lib/python3.6/site-packages/redis/connection.py", line 201, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.

Error in sys.excepthook:
Traceback (most recent call last):
  File "/projappl/project_2003107/anaconda3/envs/analytics-zoo/lib/python3.6/site-packages/redis/connection.py", line 559, in connect
    sock = self._connect()
  File "/projappl/project_2003107/anaconda3/envs/analytics-zoo/lib/python3.6/site-packages/redis/connection.py", line 615, in _connect
    raise err
  File "/projappl/project_2003107/anaconda3/envs/analytics-zoo/lib/python3.6/site-packages/redis/connection.py", line 603, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/projappl/project_2003107/anaconda3/envs/analytics-zoo/lib/python3.6/site-packages/redis/connection.py", line 1192, in get_connection
    connection.connect()
  File "/projappl/project_2003107/anaconda3/envs/analytics-zoo/lib/python3.6/site-packages/redis/connection.py", line 563, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 10.140.1.182:63178. Connection refused.

Original exception was:
Traceback (most recent call last):
  File "/projappl/project_2003107/anaconda3/envs/analytics-zoo/lib/python3.6/site-packages/ray/worker.py", line 2322, in wait
    worker.current_task_id,
  File "python/ray/_raylet.pyx", line 269, in ray._raylet.RayletClient.wait
  File "python/ray/_raylet.pyx", line 60, in ray._raylet.check_status
Exception: [RayletClient] Raylet connection closed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "analytics-zoo.py", line 51, in <module>
    main(args.train_path, args.pred_path, args.n_pred, args.dt, args.target, args.time_limit_min)
  File "analytics-zoo.py", line 32, in main
    pipeline = tsp.fit(df_train, resources_per_trial={"cpu": 4}, recipe=BayesRecipe(num_samples=100000))
  File "/projappl/project_2003107/anaconda3/envs/analytics-zoo/lib/python3.6/site-packages/zoo/automl/regression/time_sequence_predictor.py", line 128, in fit
    remote_dir=remote_dir)
  File "/projappl/project_2003107/anaconda3/envs/analytics-zoo/lib/python3.6/site-packages/zoo/automl/regression/time_sequence_predictor.py", line 261, in _hp_search
    searcher.run()
  File "/projappl/project_2003107/anaconda3/envs/analytics-zoo/lib/python3.6/site-packages/zoo/automl/search/RayTuneSearchEngine.py", line 161, in run
    raise_on_failed_trial=False
  File "/projappl/project_2003107/anaconda3/envs/analytics-zoo/lib/python3.6/site-packages/ray/tune/tune.py", line 255, in run
    runner.step()
  File "/projappl/project_2003107/anaconda3/envs/analytics-zoo/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 269, in step
    self._process_events()  # blocking
  File "/projappl/project_2003107/anaconda3/envs/analytics-zoo/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 433, in _process_events
    trial = self.trial_executor.get_next_available_trial()  # blocking
  File "/projappl/project_2003107/anaconda3/envs/analytics-zoo/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 299, in get_next_available_trial
    [result_id], _ = ray.wait(shuffled_results)
  File "/projappl/project_2003107/anaconda3/envs/analytics-zoo/lib/python3.6/site-packages/ray/worker.py", line 2322, in wait
    worker.current_task_id,
  File "/projappl/project_2003107/anaconda3/envs/analytics-zoo/lib/python3.6/site-packages/pyspark/context.py", line 270, in signal_handler
    raise KeyboardInterrupt()
KeyboardInterrupt
