WARNING - Received unrecognized parameter ensemble_download_models_timeout_sec
Running on local machine
Parent Run ID: AutoML_8f842d61-ca1e-4413-a6f1-c9eae485d187

WARNING - Received unrecognized parameter ensemble_download_models_timeout_sec
Traceback (most recent call last):
  File "/projappl/project_2003107/anaconda3/envs/azure_automl/lib/python3.7/site-packages/azureml/automl/runtime/shared/file_cache_store.py", line 330, in _create_temp_dir
    return tempfile.mkdtemp(dir=cache_path)
  File "/projappl/project_2003107/anaconda3/envs/azure_automl/lib/python3.7/tempfile.py", line 366, in mkdtemp
    _os.mkdir(file, 0o700)
OSError: [Errno 122] Disk quota exceeded: '/scratch/project_2003107/cache/tmpcscmywwp'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "azure_automl.py", line 72, in <module>
    main(args.train_path, args.pred_path, args.n_pred, args.dt, args.target, args.time_limit_min)
  File "azure_automl.py", line 33, in main
    best_run, fitted_model = experiment.submit(automl_config, show_output=True).get_output()
  File "/projappl/project_2003107/anaconda3/envs/azure_automl/lib/python3.7/site-packages/azureml/core/experiment.py", line 211, in submit
    run = submit_func(config, self.workspace, self.name, **kwargs)
  File "/projappl/project_2003107/anaconda3/envs/azure_automl/lib/python3.7/site-packages/azureml/train/automl/automlconfig.py", line 100, in _automl_static_submit
    show_output)
  File "/projappl/project_2003107/anaconda3/envs/azure_automl/lib/python3.7/site-packages/azureml/train/automl/automlconfig.py", line 258, in _start_execution
    automl_run = _default_execution(experiment, settings_obj, fit_params, True, show_output, parent_run_id)
  File "/projappl/project_2003107/anaconda3/envs/azure_automl/lib/python3.7/site-packages/azureml/train/automl/automlconfig.py", line 124, in _default_execution
    return automl_estimator.fit(**fit_params)
  File "/projappl/project_2003107/anaconda3/envs/azure_automl/lib/python3.7/site-packages/azureml/train/automl/_azureautomlclient.py", line 357, in fit
    parent_run_id=parent_run_id)
  File "/projappl/project_2003107/anaconda3/envs/azure_automl/lib/python3.7/site-packages/azureml/train/automl/runtime/_runtime_client.py", line 320, in _fit_local
    run_id=cast(str, self.azureautomlclient.parent_run_id))
  File "/projappl/project_2003107/anaconda3/envs/azure_automl/lib/python3.7/site-packages/azureml/train/automl/runtime/_cachestorefactory.py", line 41, in get_cache_store
    return FileCacheStore(path=temp_location, task_timeout=task_timeout)
  File "/projappl/project_2003107/anaconda3/envs/azure_automl/lib/python3.7/site-packages/azureml/automl/runtime/shared/file_cache_store.py", line 63, in __init__
    self.path = _create_temp_dir(path)
  File "/projappl/project_2003107/anaconda3/envs/azure_automl/lib/python3.7/site-packages/azureml/automl/runtime/shared/file_cache_store.py", line 338, in _create_temp_dir
    ) from e
azureml.automl.core.shared.exceptions.CacheException: CacheException:
	Message: Cache operation ('initialization') failed due to an OS error. This is most commonly caused due to insufficient resources on the OS (e.g. process limits, disk space) or inadequate permissions on the project directory (/scratch/project_2003107). Error details: [Errno 122] Disk quota exceeded: '/scratch/project_2003107/cache/tmpcscmywwp'.
	InnerException: OSError: [Errno 122] Disk quota exceeded: '/scratch/project_2003107/cache/tmpcscmywwp'
	ErrorResponse 
{
    "error": {
        "code": "UserError",
        "message": "Cache operation ('initialization') failed due to an OS error. This is most commonly caused due to insufficient resources on the OS (e.g. process limits, disk space) or inadequate permissions on the project directory (/scratch/project_2003107). Error details: [Errno 122] Disk quota exceeded: '/scratch/project_2003107/cache/tmpcscmywwp'.",
        "target": "cache-init",
        "inner_error": {
            "code": "Conflict",
            "inner_error": {
                "code": "CacheOperation"
            }
        }
    }
}
